# Generated by Django 3.2.7 on 2021-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imagemodel_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
