# Generated by Django 3.2.7 on 2021-09-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imagemodel_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='original_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.imagemodel'),
        ),
    ]
